FF_CONFIGURE="--enable-version3 --disable-debug  --disable-ffplay --enable-static --disable-shared --disable-encoders --enable-encoder=libmp3lame --enable-libmp3lame --enable-nonfree --disable-parsers --enable-demuxer=mp3 --disable-muxers --enable-muxer=mp3 --disable-decoders --enable-decoder=mp3"
FF_CFLAGS=""
FF_CXXFLAGS=""
FF_LDFLAGS=""
GIT_BRANCH="master"
LICENSE_FILE="COPYING.LGPLv3"
